# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Schoolender' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Schoolender

  target 'SchoolenderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SchoolenderUITests' do
    # Pods for testing
  end

pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Database'

end
